// Every icon the app uses, named for what it means rather than what it draws.
//
// Components import from here, never from the icon package directly — so changing icon
// pack is this one file. Bootstrap Icons, MIT licensed.
//
// One exception: src/components/ui/dropdown-menu.tsx is generated by the shadcn CLI and
// imports lucide-react itself. Leave it; it's regenerated on update.

export {
  ArrowLeft as ArrowLeftIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronDown as ChevronDownIcon,
  Check as CheckIcon,
  X as CloseIcon,
  List as MenuIcon,
  CameraVideo as OnlineIcon,
  PlayFill as PlayIcon,
  PauseFill as PauseIcon,
  ArrowCounterclockwise as ReplayIcon,
  PersonFill as GuestIcon,
  Trash as RemoveIcon,
  Gear as SettingsIcon,
  Pencil as EditIcon,
  PlusLg as PlusIcon,
  EnvelopePaperHeartFill as NewEventIcon,
  EnvelopeFill as EnvelopeIcon,
  EnvelopeCheckFill as AttendingIcon,
  EnvelopeSlashFill as NotAttendingIcon,
  Cake2Fill as BirthdayCakeIcon,
  Floppy2 as SaveIcon,
  BalloonHeart as PublishEventIcon,
  Sun as LightThemeIcon,
  Moon as DarkThemeIcon,
  Translate as LanguageIcon,
  Google as GoogleIcon,
  Discord as DiscordIcon,
  Spotify as SpotifyIcon,
  LockFill as LockIcon,
  Github as GithubIcon,
  GiftFill as WishlistIcon,
  BellFill as NotificationIcon,
  PeopleFill as MembersIcon,
  Images as PhotosIcon,
  Palette as DesignIcon,
  Camera2 as AddToArchiveIcon,
  SlashCircle as NotYetIcon,
  FolderFill as DriveIcon,
  GeoAlt as MapPinIcon,
  BoxArrowUpRight as ExternalLinkIcon,
  BoxArrowRight as SignOutIcon,
  HeartFill as HeartIcon,
  HourglassSplit as PendingIcon,
  LightbulbFill as SuggestionIcon,
  CalendarCheckFill as ChooseDateIcon,
  // Event categories
  MusicNoteBeamed as MusicIcon,
  Balloon as PartyIcon,
  Airplane as TripIcon,
  Signpost as HikeIcon,
  Trophy as SportIcon,
  Controller as GamingIcon,
  EggFried as FoodIcon,
  ClipboardCheck as BoardMeetingIcon,
  Cake2 as BirthdayIcon,
  CalendarEvent as OtherEventIcon,
} from "react-bootstrap-icons"

/**
 * What an icon looks like to the rest of the app.
 *
 * Deliberately structural rather than the icon pack's own type, so nothing outside this
 * file depends on which pack is installed.
 */
export type IconComponent = React.ComponentType<{ className?: string }>
