// Every icon the app uses, named for what it means rather than what it draws.
//
// Components import from here, never from the icon package directly — so changing icon
// pack is this one file. Bootstrap Icons, MIT licensed.
//
// One exception: src/components/ui/dropdown-menu.tsx is generated by the shadcn CLI and
// imports lucide-react itself. Leave it; it's regenerated on update.

export {
  ArrowLeft as ArrowLeftIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  Check as CheckIcon,
  Gear as SettingsIcon,
  Pencil as EditIcon,
  PlusLg as PlusIcon,
  Sun as LightThemeIcon,
  Moon as DarkThemeIcon,
  Display as SystemThemeIcon,
  Translate as LanguageIcon,
  // Event categories
  MusicNoteBeamed as MusicIcon,
  Balloon as PartyIcon,
  Airplane as TripIcon,
  Signpost as HikeIcon,
  Trophy as SportIcon,
  EggFried as FoodIcon,
  ClipboardCheck as BoardMeetingIcon,
  Cake2 as BirthdayIcon,
  CalendarEvent as OtherEventIcon,
} from "react-bootstrap-icons"

/**
 * What an icon looks like to the rest of the app.
 *
 * Deliberately structural rather than the icon pack's own type, so nothing outside this
 * file depends on which pack is installed.
 */
export type IconComponent = React.ComponentType<{ className?: string }>
